### ISSUE TITLE
Indent rules for line after “{”

### ISSUE THREAD

**Issue by klmr** [jcfaria/Vim-R-plugin#133]
The indent rules for Vim-R are generally very sensible but they fail in cases such as this ([testthat](https://github.com/hadley/testthat) code, but the same situation is generally applicable):

```r
test_that('the function works', {
          |
})
```

The position of the cursor is indicated by “|”, and I think it’s uncontroversial to call this wrong: in such a case, we want to simply shift the indent by `shiftwidth` from the previous level, rather than aligning it with the previous opening parenthesis.

I’ve read the FAQ and I realise this may be related to #77 but it looks sufficiently dissimilar – maybe there’s hope?

**Comment by jalvesaq** [comment]
I deleted from the Vim-R-plugin the files that are already distributed as official Vim runtime files. Now, there is a new repository with these files: https://github.com/jalvesaq/R-Vim-runtime

Since the official runtime files are no longer in this repository, I'm closing this bug. This bug is already described in the *Known bugs* section of the README.md, and new bugs should be reported in the new repository.
