### ISSUE TITLE
Set working directory in OSX when using StartR_OSX

### ISSUE THREAD

**Issue by jomuller** [jcfaria/Vim-R-plugin#152]
## What I did ?

When one try to launch *R* with *vim-r-plugin* in *OSX* without *tmux*, the application *R.app* is called.

## What I got ?

The *R.app* is properly lauched, but the working directory is the home user.

## What I expect ?

To open the *R.app* and set the working directory the same that the vim one. It's the same behaviour that we have when launching *R* with *vim-r-plugin* in a *tmux* environment.

## Clue to fix this

Because it's not possible to send options to *R.app*, the solution should be to add a call in the `StartR_OSX()` to change the working directory. Maybe something like:

    call SendCmdToR("setwd(" . expand("%:p:h") . ")")

I tried to add it to the `StartR_OSX()` function but it didn't work and my knowledge in vim script hacking is low.

I already search for this issue on the [Google Group](https://groups.google.com/forum/#!searchin/vim-r-plugin/mac$20OR$20OSX$20AND$20%22working$20directory%22) and in these issues without any result. 

## Thank you

Thank you for this fantastic plugin. It simplified my daily use of R!

**Comment by jalvesaq** [comment]
Thanks for reporting the problem! Your code is missing the quotes around the path. Where did you put the line above? After the `WaitVimComStart()`?
Even when vimcom starts, R may not be ready to receive commands yet. So it may be better to add at least a short sleep before the command. Does the code below work?

```vim
    if WaitVimComStart()
        call SendToVimCom("\005B Update OB [StartR]")
        sleep 200m
        call SendCmdToR("setwd('" . expand("%:p:h") . "')")
    endif
```

I don't have a Mac to make tests...

**Comment by jalvesaq** [comment]
I think the plugin should send to the R Console only commands triggered by the user. So, it will better to send the command to vimcom instead. Can you, please, try this:

```vim
    if WaitVimComStart()
        call SendToVimCom("\005B Update OB [StartR]")
        sleep 200m
        if g:vimrplugin_vim_wd == 0
            call SendToVimCom("\x08" . $VIMINSTANCEID . "setwd('" . expand("%:p:h") . "')")
        endif
    endif
```

**Comment by jomuller** [comment]
Thank you for this fast reply!

I tried both options. I add your lines in the `StartR_OSX()`.

- First one give me an error message saying "SendCmdToR" function is not defined.
- Second one, don't seems to change the working directory. 

Is there an easy way to debug a vim script ? e.g. placing a browser on this line, like in *R*?

I will explore this further.

**Comment by jalvesaq** [comment]
Are you using the last released version of the plugin? The function SendToVimCom was g:SendToVimCom (a pointer to the real function) in previous releases.

**Comment by jomuller** [comment]
You have right. I upgraded vim-r-plugin. But I have new bugs, espacially the message 

> Waiting vimcom loading...

and then

> The package vimcom wasn't loaded yet.

I change the time of vimcom wait in my ~/.vimrc

```vim
let vimrplugin_vimcom_wait = 10000
```

But that's strange because when it's writen "Waiting vimcom loading...", i'm already able to send lines from vim to R.

Furthermore, I wrote `r options(vimcom.verbose = 4)` in my `~/.Rprofile` but I didn't have any message now (I had some with the previous version). I checked manually in R: vimcom is properly loaded during R startup.

I also tried the various fixes you proposed without succes for the moment.

Well I'm little bit confused. I will explore this next week end. Thank's for the help!

**Comment by jalvesaq** [comment]
Vim and R have three channels of communication:

   - *From Vim to R Console*. Always works because it does not depend on either Vim's 'clientserver' feature or vimcom.
   - *From Vim to vimcom*. It only works if the vimcom package was properly built and is loaded, and if vimcom recognizes that R was called by the Vim-R-plugin.
   - *From vimcom to Vim server*. In addition to the requirement above, it also requires that Vim has the 'clientserver' feature enabled.

On Mac OS X, the vimcom package may be built in two different ways:

   - Without support for Vim's clientserver feature based on the X Server (the default).
   - With support for Vim's clientserver feature based on the X Server (only if you pass the argument `--enable-clientserver`).

MacVim is a Cocoa application and its clientserver feature does not depend on X. The support for the X11 based clientserver feature would only slow down R startup because the X Server would be automatically started (and would never be used). When vimcom notes that it was called by MacVim, it tries to send messages by running:

```sh
/path/to/MacVim.app/Contents/MacOS/Vim --servername VIM --remote-expr MESSAGE
```

The plugin is not very well tested on Mac OS X, but last week I have had the opportunity to test it with MacVim, and it worked in two configurations:

   - MacVim and Rapp.
   - MacVim and R in an external terminal emulator (`let vimrplugin_applescript = 0`).

The communication from vimcom to Vim does not work with MacVim.app/Contents/MacOS/Vim because the Vim application that comes with MacVim doesn't have the 'clientserver' feature.

I couldn't test, but I believe that it will also work with the combination of (1) Vim built by the user with support for the 'clientserver' feature based on X11, running inside Tmux and called with the argument `--servername VIM` and (2) vimcom built with `--enable-clientserver` configure argument.

**Comment by jalvesaq** [comment]
The error messages that you get mean that the C library was not loaded by vimcom. And this means that some environment variable do not have valid values, but I don't know the reason. What is the output in R of:

```s
Sys.getenv("VIMRPLUGIN_TMPDIR")
Sys.getenv("VIMRPLUGIN_COMPLDIR")
```

Since you are trying to understand how the plugin works, you can look at `VimCom/R/vimcom.R` to know how these variables define whether the C library is loaded or not.

**Comment by jomuller** [comment]
Thank you for this explanation! Reading the documentation, I was starting to understand this but your explanation is very clear.

My vim is build with the server option (don't remeber the exact name) and I call it always with --servername VIM (it's an alias in my .bash_profile). Then this part is OK.

Unfortunately, I wasn't able to build Vimcom package with the option `--enable-clientserver`. I

> R> install.packages("VimCom", type ="source", repo = NULL,
> + configure.args = "--enable-clientserver")
> Installing package into ‘/Users/jomuller/Library/R/3.1/library’
> (as ‘lib’ is unspecified)
> * installing *source* package ‘vimcom’ ...
> checking for gcc... gcc
> checking whether the C compiler works... yes
> checking for C compiler default output file name... a.out
> checking for suffix of executables...
> checking whether we are cross compiling... no
> checking for suffix of object files... o
> checking whether we are using the GNU C compiler... yes
> checking whether gcc accepts -g... yes
> checking for gcc option to accept ISO C89... none needed
> checking how to run the C preprocessor... gcc -E
> checking for X... no
> 
> Information about X11:
>     x_includes     : NONE
>     x_libraries    : NONE
>     X_CFLAGS       :
>     X_PRE_LIBS     :
>     X_EXTRA_LIBS   :
>     X_LIBS         :
> 
> configure: creating ./config.status
> config.status: creating src/Makevars
> ** libs
> clang -dynamiclib -Wl,-headerpad_max_install_names -undefined dynamic_lookup -> single_module -multiply_defined suppress -L/Library/Frameworks/R.framework/> Resources/lib -L/usr/local/lib -o vimcom.so vimcom.o vimremote.o vimthings.o -> lX11 -F/Library/Frameworks/R.framework/.. -framework R -Wl,-framework -Wl,> CoreFoundation
> ld: library not found for -lX11
> clang: error: linker command failed with exit code 1 (use -v to see invocation)
> make: *** [vimcom.so] Error 1
> ERROR: compilation failed for package ‘vimcom’
> * removing ‘/Users/jomuller/Library/R/3.1/library/vimcom’
> Message d'avis :
> In install.packages("VimCom", type = "source", repo = NULL, configure.args = "-> -enable-clientserver") :
>   l'installation du package ‘VimCom’ a eu un statut de sortie non nul> 

There must be a dependency but (libxext or something like that) but I did't figure out how to install it on my mac. Will try it on my Ubuntu box but I don't think I should be useful.

**Comment by jalvesaq** [comment]
On Ubuntu, probably, it will work because it is what I use, and there is no need to pass any configure argument to vimcom.

On OS X you perhaps have to install X Quartz. I have put this information at http://www.lepem.ufc.br/jaa/r-plugin.html#r-plugin-nox but I am not sure if the instructions work.

**Comment by jomuller** [comment]
You are awesome!
It's work!

My error was I had already X11 installed (last version) and reinstalling it, I was able to build the package. I can't explain this. My system is a mess (I didn't reinstalled it since almost 2 years, only upgrades).

I will send you a pull request with the change you suggested if you want.

And I will write a reproductible way to install properly all this stuff on mac.

Thank you again!

**Comment by jalvesaq** [comment]
Good! I'm waiting for the pull request and your text. I may add a link to your text in the plugin's documentation.

**Comment by jomuller** [comment]
There is still a little problem: the working directory is not set if 
```vim
let vimrplugin_vim_wd = 1
```
What should be the behaviour in this case? I find it very useful to have the always R opened with the same working directory that Vim has, whatever is the buffer is opened.

For the moment I withdrawed the conditionnal

```vim
    if WaitVimComStart()
        call SendToVimCom("\005B Update OB [StartR]")
        sleep 200m
       " if g:vimrplugin_vim_wd == 0
            "Set vim's working directory as R working directory
            call SendToVimCom("\x08" . $VIMINSTANCEID . 'setwd("' . expand("%:p:h") . '")')
       " endif
    endif
```

Seems to work as I expect.

I just note it here to think about it. I will explore that next week end.

**Comment by jalvesaq** [comment]
You are right. The code was incomplete. I think that what will fully follow the documentation is:

```vim
        if g:vimrplugin_vim_wd
            call SendToVimCom("\x08" . $VIMINSTANCEID . 'setwd("' . getcwd() . '")')
        else
            call SendToVimCom("\x08" . $VIMINSTANCEID . 'setwd("' . expand("%:p:h") . '")')
        endif
```

**Comment by jomuller** [comment]
I started to write the text about the installation of your plugin with MacVim here:
http://jomuller.fr/?p=413

It's need still proofreading (will do it this afternoon) and I will try again the steps on a fresh install of Mac OS X. I wrote it with data scientist as target audience who want to try MacVim with R with no prior installation.

**Comment by jalvesaq** [comment]
I think it is useful because it is specific to MacVim. The instructions in the plugin documentation is split for Windows, Linux and Mac OS X, and there are too many notes about exceptions.

While reading you text, I noted that my graphic was wrong. The TCP client on vimcom.so only exists in the package `nvimcom`, which does not rely on Vim's 'clientserver' feature. I fixed it now.
