### ISSUE TITLE
global plugin with Julia

### ISSUE THREAD

**Issue by michaellindon** [jcfaria/Vim-R-plugin#166]
![screenshot from 2015-03-28 16 35 34](https://cloud.githubusercontent.com/assets/4892846/6882814/131bb6e6-d569-11e4-8109-6a67d4811f26.png)

I have been trying to get the vim-r-plugin to work with julia. I have been able to send code line by line to the julia REPL but if i try localleader bb or localleader ss it fails. The above error os for localleader ss.

If i try localleader bb it says "file has no mark!"

Could you please suggest a solution?

**Comment by jalvesaq** [comment]
Did the change https://github.com/jcfaria/Vim-R-plugin/commit/18d7a3b521e6c024b65ab0e6a6014708db7fc513 solve the problem?

**Comment by jalvesaq** [comment]
I do not have julia installed, so, I can't test the "file has no mark" problem. In fact, I don't use the script global_r_plugin.vim and I would be happy if someone could maintain it separately. It could be included in the Vim-R-plugin with the option `vimrplugin_source`.

**Comment by jalvesaq** [comment]
I guess that the best thing to do is to delete the file global_r_plugin.vim because I don't use it, unless someone wants to maintain it.

Although I only use R, I created a plugin that can send lines of code to *julia*, *haskell*, *lisp*, *python* and *ruby*: https://github.com/jalvesaq/vimcmdline
It only works with Neovim, but I may add support to Tmux latter and, then, it would also work with Vim.

**Comment by michaellindon** [comment]
awesome! I cant wait to give this a try

**Comment by jalvesaq** [comment]
I added support for Tmux. Please, let me see if it works for you.

**Comment by jalvesaq** [comment]
I am closing this issue. I will soon delete the global_r_plugin.vim because I believe that the use of the new plugin is better than trying to adapt this plugin to be used with interpreters other than R.
