### ISSUE TITLE
start R from an edited file, vim will get E341: Internal error: lalloc(0, )

### ISSUE THREAD

**Issue by qifei9** [jcfaria/Vim-R-plugin#168]
if use "\rf" to start R from an edited file, vim will get E341: Internal error: lalloc(0, ). If start R from un-edited file, everything is OK.

reproduce:
in terminal,
1, start tmux
2, vim test.r
3, edit the file
4, save the file, *optional*
5, "\rf"

vim version 7.4.663
plugin version 1.2.2

**Comment by jalvesaq** [comment]
The bug is in Vim, but it does not happen here (Vim 7.4.691), and development version of Vim-R-plugin and vimcom.

**Comment by qifei9** [comment]
It also happens for me in vim 7.4.663 with development version of Vim-R-plugin and vimcom.

If vim get this error on one file, it will for ever get the error on that file. really annoying.

**Comment by jalvesaq** [comment]
Thanks for installing the development versions of Vim-R-plugin and vimcom! But since the bug is Vim, it may have been fixed by one of the patches after 663 (the list of patches is on ftp://ftp.vim.org/pub/vim/patches/7.4/README). Can you compile Vim from the mercurial repository to get the last development version? The instructions are on Vim's website: http://www.vim.org/mercurial.php

There is a suggestion to configure the building of Vim `--with-feature=huge`: https://groups.google.com/forum/#!msg/vim_dev/EIE_CMLl96w/5a4isuK4JtgJ

**Comment by jalvesaq** [comment]
I think that this bug was fixed by Vim patch 7.4.866...
