### ISSUE TITLE
comment symbols after \o not consistent with "indent settings"

### ISSUE THREAD

**Issue by scheike** [jcfaria/Vim-R-plugin#170]
seems that \o does not use the string  that can otherwise be set by

vimrplugin_indent_commented   r_indent_ess_comments   string
                 1                        0                #
                 0                        0                #
                 1                        1                ##
                 0                        1                ###

but always just uses "#"

**Comment by jalvesaq** [comment]
In fact, it is "# " (with a space after the #), and is controlled by vimrplugin_rcomment_string. The purpose of using this variable was to let the user to add a space after the #), but perhaps I should eliminate the option and control the string with the indent variables. The doubt is: *Should the space be unconditionally added to the string or not*?

Anyway, the option is not properly documented. It only appears in the *Usage* section.

**Comment by scheike** [comment]
Thanks, for me it is useful to be able to have "### " rather than just "# " just as
it is possible with the settings for the comments. The space is fine, and I can not imagine
why you could not live the space.

another funny little thing is that if you pass a line that start with "-" to R then things
break down.

________________________________

**Comment by jalvesaq** [comment]
The two bugs reported here are fixed. I kept the option `vimrplugin_rcomment_string`, but now its default value is adjusted according to `vimrplugin_indent_commented` and `r_indent_ess_comments`.

**Comment by scheike** [comment]
discovered that you have taken \pe and \pa away from us (and similarly for the other send commands), sorry to hear that, these are very useful commands to make the alternation between echo and no echo easy.

**Comment by jalvesaq** [comment]
Some people have complained about this. The option of using `vimrplugin_source_args` seems not to be good enough. What is the advantage of using the *echo* variant of the send commands? The code is already in the R script, so why the need to see it echoed in the R Console?

**Comment by zeloff** [comment]
Personally, I used it a lot when writing Rmd/Rnw documents with ggplots in it. If the code containing the plot is `source()`d without `echo`, the code is evaluated but the plot isn't shown (the output of `ggplot` needs to be explicitly `print()`ed for this). However, if the code is echoed when `source()`d, the plot shows up as expected.
This has to do with the fact that (when writing on the R console)
```r

``` 
This isn't a problem when compiling the document, since `knitr` handles the lack of `print()`ing of ggplots.

**Comment by jalvesaq** [comment]
I deleted the echo commands because I could not think in a use for them. They are back now: https://github.com/jcfaria/Vim-R-plugin/commit/ddb77d74721b2f42c2a5d180c3d6ded1567e1be3

**Comment by scheike** [comment]
the problem  depends on what code you transfer for example

cox3=coxph(Surv(alderf,agefinal,doed_cpr==1)~
           prop(zlhcut),data=zvalsmoke)
  cox3
  print(cox3)

clearly with the print(cox3) no echo is needed, but  if you just use cox3 then you get no
output,

Thanks and great to have it back.

Another feature on my wish list is to be able to send a chunk to R and get the output
back in a file almost as ao (preferably this should use the workspace as hand). This is
useful for communicating with other people about specific analyses.

Thanks
________________________________

**Comment by jalvesaq** [comment]
Do you know the `\o` command? It inserts the output of `print(current_line)` below the line being edited, but the output is inserted commented out with `#`. What you are requesting is that the output is not commented and is inserted in a new buffer (I would put it in a new tab). However, if you need to show results for other people, the best option is the use of Rnoweb (R + LaTeX) or Rmd (R + Markdown).

**Comment by scheike** [comment]
Yes I know the \o command that is also quite nice.  But the \ao command that
runs the entire file and puts the output in separate tab is also very nice and brings you back
to vim. Sometimes this could be nice to run for just a part of the document.

best regards and thanks

Thomas


________________________________

**Comment by jalvesaq** [comment]
I can do this: `\ao` in Normal mode runs `R CMD BATCH` on the entire file (as it already does) and in Visual mode sends only the selection to be sourced by the current R process and puts the output in another tab. Implementing in this way, we don't need a new key binding.

**Comment by jalvesaq** [comment]
I implemented the requested feature in a new branch: https://github.com/jcfaria/Vim-R-plugin/tree/get_sel_output
I will wait some time for comments before committing the changes into the master branch.

The key binding for triggering the command is `\st` ("s" from *selection* and "t" from *tab*) but if anyone thinks that another key binding would be more intuitive, please, comment.

**Comment by scheike** [comment]
wonderful ! I will try it out, it is not possible to use \ao (because we are in visual mode) ?

best T
________________________________

**Comment by zeloff** [comment]
Just my two cents about `\ao` in visual mode. Assuming in visual mode you have selected a part of the file, I think a `\a*` mapping would be inappropriate, since **s**elections are associated with `\s*` mappings while `\a*` mappings are reserved for "**a**ll file". Thus, I think using `\ao` for sending parts of the file in visual mode, as Jackson suggested three comments ago, might be inconsistent and counter-intuitive. Nothing against using it in visual mode to send the whole file, of course.

**Comment by scheike** [comment]
cool, of course there is some logic to the command name and i can see that ao might not
be consistent

works nicely when there is no wait as in

x=10
x


but with waiting nothing comes up

for (i in 1:100000000) x <- i                                   │

has to do with size of 100000000 (the waiting time ?)

best

T

________________________________

**Comment by jalvesaq** [comment]
@zeloff  is right about my initial proposal of using `\ao`. But instead of `\st` it can be `\so` ("o" from output) or anything else. I have no preference.

The function `ReadEvalReply()` (*r-plugin/common_global.vim*) waits 2 seconds for R reply and gives up if there is no reply within this time. There are two ways of fixing this:

  - Create an option, `vimrplugin_wait_time` that you could configure in your *vimrc*.
  - Do not wait at all. The vimcom library would send a message to Vim informing that the job was finished.

The problem of the first option is that it is yet another option, and it is not a dynamic solution. You have to know beforehand that you need more time. The problem of the second option is that if the job takes too long to finish, you may start to edit the script and, while you are typing something, a new tab will be opened and break your flow of work.

**Comment by scheike** [comment]
"so" sounds very good (but as you say this is not very important), and if the output is simply put in a tab when it is finshed (without going there) it  would be
just perfect for my work-flow where I often run things that take a while and it is nice to be able to continue with other
things in the file, I noticed that it also finished the job but due to the waiting did not return the output.

thanks and best regards

________________________________

**Comment by jalvesaq** [comment]
I will change the key binding to `\so` and then merge the branch. Latter, I will create a new branch to test the possibility of opening a new tab "without going to it". Actually, this is not possible with Vim. We cannot create a buffer and change its contents without going there. What I can do is to go back to the working buffer.

**Comment by jalvesaq** [comment]
This discussion should continue at https://github.com/jcfaria/Vim-R-plugin/issues/173
