### ISSUE TITLE
ReplaceUnderS() not compatible with vim macros or repeat insert.

### ISSUE THREAD

**Issue by jdthorpe** [jcfaria/Vim-R-plugin#194]
The default mapping of the Underscore character (`_`) to the left assignment operator (`<-`) is handy to be sure, but the implementation uses a call to  `ReplaceUnderS()`:

```
    <Esc>:call ReplaceUnderS()<CR>a
```

Which has the major drawback that vim insert commands cannot be repeated (`.`) or used in macros (`q` + `@`) if the text that is inserted includes an R assignment statement or an underscore character.    I appreciate the flexibility of `ReplaceUnderS()`, but the default case can be replaced with:

```
    iabb <buffer> _  <- 
    inoreabbrev <buffer> __ _
```

without this major drawback. This implementation does not insert the right assignment operator in the middle of  word (e.g. `dplyr::anti_join()`, which is a benifit, IMHO), so it does not replicate the current mapping exactly.

Hence, I would encourage this addition to `RCreateEditMaps()`:

````
    if g:vimrplugin_assign == 1 || g:vimrplugin_assign == 2
        if g:vimrplugin_assign_map == "_"
            iabb <buffer> _  <- 
            inoreabbrev <buffer> __ _
        else
            silent exe 'imap <buffer><silent> ' . g:vimrplugin_assign_map . ' <Esc>:call ReplaceUnderS()<CR>a'
        endif
    endif
```

Of course, users can work around this issue by adding this in the `.vimrc`:

```
    let g:vimrplugin_assign = 0
    if !exists("autocommands_loaded")
        let autocommands_loaded = 1
        au FileType r iabb <buffer> _ <-
        au FileType r inoreabbrev <buffer> __ _
    endif
```

but that's a more advanced solution for many vimmers.

On a completely separate note, the ' magrittr::%>%' operator is gaining popularity, and I would propose adding this as a standard macro:

```
    iabb <buffer> >< %>%
````

**Comment by jalvesaq** [comment]
You proposal of change would make the function `ReplaceUnderS` not being called when the `vimrplugin_assign_map` was `_`, and the command `iabb _ <-` does not seem that useful to me because I have to press `<Space>_<Space>` to get `<-`. Note also that if you put a mapping in *common_global.vim*, it will be executed only in the first R buffer opened during a Vim's session. It should be added to *common_buffer.vim*.

So, I suggest the addition of a new valid value for `vimrplugin_assign`, and the following text to the plugin's documentation:

If the value of vimrplugin_assign is 3, the plugin will run the following command in each buffer containing R code (R, Rnoweb, Rhelp, Rrst, and Rmd):

```vim
iabb <buffer> _  <- 
```

That is, the underscore will be replaced with the assign operator only if it is preceded by a space and followed by a non-word character.

**Comment by jalvesaq** [comment]
Regarding the `%>%`  operator, I did not know about it. But I prefer do not add support for commands of many packages. We may let each user do this according to their preferences.

**Comment by jdthorpe** [comment]
Both of the above comments sound reasonable,  thanks.  For what it's worth, the `%>%` is popular b/c of it's frequent use in the `dplyr` and `ggplot2` packages, and allows chaining of statements...

**Comment by jalvesaq** [comment]
Thanks for reporting the issue!
