### ISSUE TITLE
Can't see R documentation and plots

### ISSUE THREAD

**Issue by DadongZ** [jcfaria/Vim-R-plugin#206]
Hi
I know the Vim-R-plugin may not be maintained any more, but after a failed switch to NvimR (may be due to I am working on server), I installed the previous version of Vim-R-Plugin.

After that, one big issue I have is when I type `?rfunctions`, I can't see anything either from terminal or browser. Also no plot can be popped up if I am trying `plot()` in R. I have spent much time online but still can't fix it and hope you could have some hints.

The other issue same as when I was installing NvimR is I got this below message when I start R from vim:

`Error: Could not bind. [vimcom]`

TYVM

**Comment by jalvesaq** [comment]
The error `Error: Could not bind` means that vimcom/nvimcom failed to start its own TCP server. Consequently, you can simply send code from Vim/Neovim to the R console. Please, read the section "The communication between R and either Vim or Neovim" at the end of [Nvim-R/README.md](https://github.com/jalvesaq/Nvim-R/blob/master/README.md).

Unfortunately, I can't fix the bug because I can't replicate it and I don't know enough about client/server stuff to guess what might be the problem.

Anyway, even if I knew the solution, I would not fix it here because Vim-R-plugin is dead. I would only make changes in Nvim-R. So, I am closing this issue.
