### ISSUE TITLE
Multiline quote as argument wrongly indented

### ISSUE THREAD

**Issue by gvfarns** [jcfaria/Vim-R-plugin#37]
Thanks so much for your work on this plugin.  I use it constantly!

I frequently use long SQL commands within sqldf() and find that the indent code consistently gets it wrong.  I wonder how difficult it would be to correct indent/vim.r so that this works right.  For example:

```
g <- sqldf('select a, b
           from aa left join bb
           on aa.date =bb.date')                                                                                                        
head(g)
```

Is indented incorrectly, with head(g) being indented as if it was a part of the sqldf argument.  Placing the second parenthesis on its own line arrives at the correct intending, but it would be nice if the code indented things correctly without the programmer having to manually work around the current behavior.

**Comment by jalvesaq** [comment]
I deleted from the Vim-R-plugin the files that are already distributed as official Vim runtime files. Now, there is a new repository with these files: https://github.com/jalvesaq/R-Vim-runtime

Since the official runtime files are no longer in this repository, I'm closing this bug. This bug is already described in the *Known bugs* section of the README.md, and new bugs should be reported in the new repository.
