### ISSUE TITLE
Error: The X Window system is required to run R in an external terminal.

### ISSUE THREAD

**Issue by groupschoof** [jcfaria/Vim-R-plugin#61]
Dear programmers,

thank your for providing Vim-R-plugin.

I have a probably easy and quick to fulfill request:

Running vim in an ssh session from within tmux I would like to have Vim-R-plugin to open a new tmux window for me.
To achieve this, I set the following in my .vimrc:

let vimrplugin_term_cmd = "tmux new-window 'R"

I tried the latter tmux command and it works, i.e. it opens a new tmux window and starts R in there. But unfortunately I get the error "The X Window system is required to run R in an external terminal".

I assume the plugin checks for a running X window system before even trying to start R?
Could you introduce a simple switch to turn that check off, please?
Something like:
vimrplugin_check_x_win_sys = 0

I for one would be very happy, indeed.

Cheers!

**Comment by DadongZ** [comment]
Hi There, I am still using the previous Vim-R-Plugin version and pretty comfortable about it settings. Recently I upgraded the linux system and got message never before "Start 'tmux' before Vim. The X Window system is required to run R in an external terminal.". The issue is, if I start tmux manually, the vim background were also changed weirdly and furhter `,rc` will start a R console in a split window rather than a new window. Do you have some suggestions?
