### ISSUE TITLE
Indenting rules don't like multi-line strings

### ISSUE THREAD

**Issue by caneff** [jcfaria/Vim-R-plugin#77]
Pretty simple example here:

```
a <- ("multi
     line
     string")
```

If you go to the next line the cursor lines itself up with in the same column as s in string.  Note that you need the parentheses around the string. Otherwise if you leave them out, it doesn't indent on the line after ```multi``` (which is fine and how other languages seem to behave). 

Also if I have 

```
a <- ("multi
     line
          indented
     string")
```

And indent with ```=ap```, the indented line gets brought back to the same indent level as everything else.  Text in strings should be left alone when indenting.

**Comment by jalvesaq** [comment]
I deleted from the Vim-R-plugin the files that are already distributed as official Vim runtime files. Now, there is a new repository with these files: https://github.com/jalvesaq/R-Vim-runtime

Since the official runtime files are no longer in this repository, I'm closing this bug. This bug is already described in the *Known bugs* section of the README.md, and new bugs should be reported in the new repository.
